USE [master]
GO

/****** Object:  Database [MySchool]    Script Date: 2022/3/12 14:14:58 ******/
CREATE DATABASE [MySchool]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MySchool', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\MySchool.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MySchool_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\MySchool_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [MySchool] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MySchool].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MySchool] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MySchool] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MySchool] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MySchool] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MySchool] SET ARITHABORT OFF 
GO

ALTER DATABASE [MySchool] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MySchool] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MySchool] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MySchool] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MySchool] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MySchool] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MySchool] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MySchool] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MySchool] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MySchool] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MySchool] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MySchool] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MySchool] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MySchool] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MySchool] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MySchool] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MySchool] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MySchool] SET RECOVERY FULL 
GO

ALTER DATABASE [MySchool] SET  MULTI_USER 
GO

ALTER DATABASE [MySchool] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MySchool] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MySchool] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MySchool] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [MySchool] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MySchool] SET QUERY_STORE = OFF
GO

USE [MySchool]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [MySchool] SET  READ_WRITE 
GO

